<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ENGSCI 304: Engineering Machine Learning II - 3&nbsp; Obtaining and visualising the dataset</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./camera_models.html" rel="next">
<link href="./basketball_application.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/print.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./visual.html">Visual data</a></li><li class="breadcrumb-item"><a href="./dataset.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Obtaining and visualising the dataset</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ENGSCI 304: Engineering Machine Learning II</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About these notes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recommended_reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Recommended reading</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./visual.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visual data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basketball_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Application: From amateur basketball video footage to player trajectories</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dataset.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Obtaining and visualising the dataset</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./camera_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Camera models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./image_tasks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Image analysis tasks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./image_modelling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Image modelling: From pixels to learned features</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./training.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Training and inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./object_detection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Object detection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Evaluation of detection models</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#view-the-videos" id="toc-view-the-videos" class="nav-link active" data-scroll-target="#view-the-videos"><span class="header-section-number">3.1</span> View the videos</a></li>
  <li><a href="#view-the-annotations" id="toc-view-the-annotations" class="nav-link" data-scroll-target="#view-the-annotations"><span class="header-section-number">3.2</span> View the annotations</a></li>
  <li><a href="#view-the-precomputed-detections" id="toc-view-the-precomputed-detections" class="nav-link" data-scroll-target="#view-the-precomputed-detections"><span class="header-section-number">3.3</span> View the precomputed detections</a></li>
  <li><a href="#generate-your-own-detections" id="toc-generate-your-own-detections" class="nav-link" data-scroll-target="#generate-your-own-detections"><span class="header-section-number">3.4</span> Generate your own detections</a></li>
  <li><a href="#annotating-the-videos" id="toc-annotating-the-videos" class="nav-link" data-scroll-target="#annotating-the-videos"><span class="header-section-number">3.5</span> Annotating the videos</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./visual.html">Visual data</a></li><li class="breadcrumb-item"><a href="./dataset.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Obtaining and visualising the dataset</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Obtaining and visualising the dataset</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>As mentioned, there is a curated version of the dataset for this application provided on Canvas. However, if you would like to obtain the original dataset, you can find it in the <a href="https://drive.google.com/drive/folders/1aWqMwQKr5xKMjqms7-raYluSlxPsGvwX">TrackID3x3 public data archive</a>.</p>
<p>Once you have obtained the course dataset you should explore it to understand its structure and contents. Some example explorations are given below. We use some terminology in what follows that you may not be familiar with, though it is hopefully clear from the context; we give more details on this terminology in the next section.</p>
<section id="view-the-videos" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="view-the-videos"><span class="header-section-number">3.1</span> View the videos</h2>
<p>Open <code>basket_S1T4_pre.mp4</code> from the course dataset and watch the clip. It is about seven seconds long and was recorded with a fixed camera. Notice the six active players, as well as the other people visible around the court. Our task is to track the six active players, rather than every person in the image. A representative frame is shown below.</p>
<div id="fig-dataset-frame50-raw" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dataset-frame50-raw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="attachments/trackid3x3-s1t4/frame50_raw.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dataset-frame50-raw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.1: Frame 50 of <code>basket_S1T4_pre</code>.
</figcaption>
</figure>
</div>
</section>
<section id="view-the-annotations" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="view-the-annotations"><span class="header-section-number">3.2</span> View the annotations</h2>
<p>The video comes with human-reviewed <strong>annotations</strong> marking the six active players. Each annotation contains a rectangular <strong>bounding box</strong> around a player and an anonymous <strong>player ID</strong>. Within this clip, the same ID refers to the same player across frames. These IDs are part of the supplied annotations.</p>
<div id="fig-dataset-frame50-annotations" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dataset-frame50-annotations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="attachments/trackid3x3-s1t4/frame50_annotations.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dataset-frame50-annotations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.2: Annotation boxes with anonymous player IDs.
</figcaption>
</figure>
</div>
<p>The file <code>ground_truth_mot.txt</code> contains these annotations as comma-separated rows, with one row per player per frame. In statistics terminology, rows represent our <strong>unit of observation</strong>, here a ‘player-and–frame’ combination, and these observations are arranged in a <strong>long</strong> format data table. Note that <strong>ground truth</strong> is the conventional name for manual/human-checked annotations even though human annotations may in fact contain errors! Here are three of the six rows for frame 50, with some column names added and unused columns omitted:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;"><code>frame</code></th>
<th style="text-align: right;"><code>track_id</code></th>
<th style="text-align: right;"><code>x_left</code></th>
<th style="text-align: right;"><code>y_top</code></th>
<th style="text-align: right;"><code>width</code></th>
<th style="text-align: right;"><code>height</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">50</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">529.00</td>
<td style="text-align: right;">414.00</td>
<td style="text-align: right;">82.00</td>
<td style="text-align: right;">143.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">50</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">975.70</td>
<td style="text-align: right;">415.64</td>
<td style="text-align: right;">81.93</td>
<td style="text-align: right;">166.28</td>
</tr>
<tr class="odd">
<td style="text-align: right;">50</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">333.92</td>
<td style="text-align: right;">310.58</td>
<td style="text-align: right;">30.47</td>
<td style="text-align: right;">89.20</td>
</tr>
</tbody>
</table>
<ul>
<li><code>frame</code> identifies the video frame, numbered from 1.</li>
<li><code>track_id</code> identifies the player within this clip.</li>
<li><code>x_left</code> and <code>y_top</code> give the image coordinates of the box’s upper-left corner, in pixels.</li>
<li><code>width</code> and <code>height</code> give the box dimensions, also in pixels.</li>
</ul>
<p>Image coordinates start at the upper-left corner: <span class="math inline">\(x\)</span> increases to the right and <span class="math inline">\(y\)</span> increases downwards. For example, the first row describes player 1 in frame 50. Its box starts at <span class="math inline">\((529, 414)\)</span> and extends 82 pixels to the right and 143 pixels down, ending at <span class="math inline">\((611, 557)\)</span>.</p>
<div id="fig-dataset-box-coordinates" class="quarto-figure quarto-figure-center quarto-float anchored" alt="Image coordinates increase rightwards and downwards. The box starts at (529, 414), is 82 pixels wide and 143 pixels high, and ends at (611, 557).">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dataset-box-coordinates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="attachments/trackid3x3-s1t4/frame50_box_coordinates.png" class="img-fluid figure-img" style="width:85.0%" alt="Image coordinates increase rightwards and downwards. The box starts at (529, 414), is 82 pixels wide and 143 pixels high, and ends at (611, 557).">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dataset-box-coordinates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.3: Coordinates and dimensions of the annotation box for player 1 in frame 50.
</figcaption>
</figure>
</div>
</section>
<section id="view-the-precomputed-detections" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="view-the-precomputed-detections"><span class="header-section-number">3.3</span> View the precomputed detections</h2>
<p>We have also (separately to the original dataset) provided <strong>object detections</strong>, or <strong>predicted boxes</strong>, produced by <a href="https://docs.ultralytics.com/models/yolo11/"><strong>YOLO11n</strong></a>, a model developed by the computer-vision software company Ultralytics. This is a <strong>pretrained object detector</strong>: its parameters were learned from other images before we used it to analyse this clip. Here we ask it to <strong>detect objects in the generic <code>person</code> category</strong>. Importantly, this is <em>not the same as detecting players</em>, which is our application or engineering target. We will return to how these models work and are trained in the <a href="./object_detection.html">object-detection chapter</a>.</p>
<p>Each predicted box comes with a <strong>confidence score</strong>, ranging from 0 to 1. Higher scores indicate stronger model support for a detection, but these are not necessarily calibrated probabilities of correctness on our task. We typically then use a <strong>confidence threshold</strong> to select which predictions to keep, e.g.&nbsp;‘keep only predictions with confidence <span class="math inline">\(\ge 0.50\)</span>’. Of course, a high score does not guarantee that a prediction is correct or relevant to our task, and we need to evaluate the model’s performance on our task.</p>
<p>The file <code>yolo11n_person_conf001.csv</code> contains the detector library’s saved predictions, produced using a low confidence threshold of 0.01, in order to save as many predictions as possible. Each row contains a predicted box, <em>here in terms of the upper-left corner and lower-right corner rather than upper-left corner and width/height</em>, plus a <code>confidence</code> column. For the illustration below, we keep only predictions with confidence <span class="math inline">\(\ge 0.50\)</span>, leaving eight of the 31 saved predictions for frame 50. At this stage we filter only by confidence, not by any other criteria which might distinguish players from non-players.</p>
<div id="fig-dataset-frame50-predictions" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dataset-frame50-predictions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="attachments/trackid3x3-s1t4/frame50_predictions_conf050.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dataset-frame50-predictions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.4: YOLO11n predicted boxes, labelled by confidence (<span class="math inline">\(\ge 0.50\)</span>).
</figcaption>
</figure>
</div>
<p>Notice that the model also detects non-players, e.g.&nbsp;an apparent coach or similar figure standing near the sideline and two observers sitting at mid court. In fact, for the two sitting observers the model only detects one of them, and the other is missed, presumably because they are sitting very close together.</p>
<p>Here are the three highest-confidence predictions for this frame, with scores and coordinates rounded to two decimal places:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;"><code>frame</code></th>
<th style="text-align: right;"><code>confidence</code></th>
<th style="text-align: right;"><code>x_min</code></th>
<th style="text-align: right;"><code>y_min</code></th>
<th style="text-align: right;"><code>x_max</code></th>
<th style="text-align: right;"><code>y_max</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">50</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">1018.13</td>
<td style="text-align: right;">509.92</td>
<td style="text-align: right;">1123.76</td>
<td style="text-align: right;">719.90</td>
</tr>
<tr class="even">
<td style="text-align: right;">50</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">332.86</td>
<td style="text-align: right;">310.63</td>
<td style="text-align: right;">363.40</td>
<td style="text-align: right;">396.43</td>
</tr>
<tr class="odd">
<td style="text-align: right;">50</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">528.20</td>
<td style="text-align: right;">415.57</td>
<td style="text-align: right;">608.95</td>
<td style="text-align: right;">551.22</td>
</tr>
</tbody>
</table>
<ul>
<li><code>frame</code> identifies the video frame, as before.</li>
<li><code>confidence</code> is the score assigned to the predicted box, not a player ID.</li>
<li><code>x_min</code> and <code>y_min</code> give the upper-left corner of the box.</li>
<li><code>x_max</code> and <code>y_max</code> give the lower-right corner of the box.</li>
</ul>
<p>These coordinates are in pixels. Since the boxes are given in terms of the upper-left and lower-right corners, we can compute the width and height of the box as <code>width = x_max - x_min</code> and <code>height = y_max - y_min</code> for comparison with the annotation boxes.</p>
<p>There is no <code>track_id</code> column here, and the rows have not been matched to the annotation rows above. <strong>A key task will be to compare the predicted boxes with the annotations</strong> and hence evaluate the detector. Later, we will link predictions across frames to carry out the tracking task.</p>
</section>
<section id="generate-your-own-detections" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="generate-your-own-detections"><span class="header-section-number">3.4</span> Generate your own detections</h2>
<p>We can generate our own detections using the <code>ultralytics</code> Python package. Here we use the pretrained YOLO11n model to perform <strong>inference</strong>: given an image, it returns predicted boxes, class labels and confidence scores, without changing its learned parameters. We will start with frame 50 of our video, so that we can compare the output with the precomputed detections above.</p>
<p>We can run this example in a Jupyter notebook on our own machine or in Google Colab. Since we are only running the pretrained model on a single frame, a GPU is not required. If using Colab, upload <code>basket_S1T4_pre.mp4</code> directly through the Files pane on the left; there is no need to mount Google Drive.</p>
<p>First, install the <code>ultralytics</code> package in the notebook. We specify the version used to generate the supplied detections:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>pip install ultralytics<span class="op">==</span><span class="fl">8.4.52</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Then import <code>YOLO</code> and load the pretrained model:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ultralytics <span class="im">import</span> YOLO</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> YOLO(<span class="st">"yolo11n.pt"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The <code>.pt</code> extension is a common convention for files saved by <strong>PyTorch</strong>, the deep-learning library used by <code>ultralytics</code>. Saving a model records its learned parameters so that they can be reused without retraining. Loading restores these parameters into the corresponding model structure; here, the <code>YOLO</code> interface handles this for us. The library downloads <code>yolo11n.pt</code> automatically if needed, so the first run requires internet access. This loads the model; it does not yet run detection on an image.</p>
<p>We use <strong>OpenCV</strong>, a library for working with images and video, to read the frame. Here we assume the video file is in the notebook’s working directory. Our dataset numbers frames from 1, whereas OpenCV uses indices starting from 0, so frame 50 has index 49.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cv2</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>frame_number <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>video <span class="op">=</span> cv2.VideoCapture(<span class="st">"basket_S1T4_pre.mp4"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>video.<span class="bu">set</span>(cv2.CAP_PROP_POS_FRAMES, frame_number <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>success, frame_bgr <span class="op">=</span> video.read()</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>video.release()</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> success:</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">RuntimeError</span>(</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"Could not read frame </span><span class="sc">{</span>frame_number<span class="sc">}</span><span class="ss">. Check the video file path."</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The image is now stored in the NumPy array <code>frame_bgr</code>. OpenCV stores its colour channels in blue–green–red (BGR) order, which we will account for when displaying it.</p>
<p>Matplotlib expects colour channels in RGB order, so we make a separate RGB array for display:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>frame_rgb <span class="op">=</span> cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>plt.imshow(frame_rgb)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">"off"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>With <code>frame_number = 50</code>, this should show the same unannotated frame displayed earlier. We keep <code>frame_bgr</code> for the next step: YOLO expects BGR channel order when we pass it a NumPy array.</p>
<p>This pretrained model is trained to recognise 80 object categories. The dictionary <code>model.names</code> maps each category’s ID to its name. We can display them all with:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> class_id, class_name <span class="kw">in</span> model.names.items():</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(class_id, class_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Examples include <code>0: person</code>, <code>1: bicycle</code>, <code>2: car</code> and <code>16: dog</code>. These are category IDs, not identifiers for individual objects. We use <code>classes=[0]</code> to keep only person detections. For example, <code>classes=[0, 2]</code> would keep person and car detections, while omitting the <code>classes</code> argument allows predictions from any of the model’s categories.</p>
<p>We can now pass the frame to the detector. We request only <code>person</code> detections and use the same low confidence threshold as the supplied CSV, leaving stricter filtering until afterwards:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> model.predict(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    source<span class="op">=</span>frame_bgr,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    classes<span class="op">=</span>[<span class="dv">0</span>],</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    conf<span class="op">=</span><span class="fl">0.01</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    iou<span class="op">=</span><span class="fl">0.70</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    device<span class="op">=</span><span class="st">"cpu"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> results[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Here <code>classes=[0]</code> selects the model’s <code>person</code> category—not a player ID. The <code>iou</code> setting controls suppression of strongly overlapping predicted boxes, which we will discuss later. It does not compare predictions with our annotations.</p>
<p>The <code>predict</code> method returns a list containing one result per input image. Since we supplied one frame, <code>results[0]</code> gives us its result.</p>
<p><code>result.boxes.conf</code> contains a confidence score for each predicted box. We select the higher-confidence predictions for display, leaving the original <code>result</code> unchanged:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>keep <span class="op">=</span> result.boxes.conf <span class="op">&gt;=</span> <span class="fl">0.50</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>display_result <span class="op">=</span> result[keep]</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>prediction_image_bgr <span class="op">=</span> display_result.plot()</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>plt.imshow(cv2.cvtColor(prediction_image_bgr, cv2.COLOR_BGR2RGB))</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">"off"</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The <code>plot()</code> method returns an image with the predicted boxes and labels drawn on it, again in BGR order. The labels show the predicted category and confidence, not a player ID.</p>
<p>We can inspect the predicted box coordinates and confidence scores directly. For example, the following prints the first three predictions:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(result.boxes.xyxy[:<span class="dv">3</span>])</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(result.boxes.conf[:<span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Each row of <code>xyxy</code> contains <code>[x_min, y_min, x_max, y_max]</code> in pixels. The corresponding entry in <code>conf</code> gives that box’s confidence score. These values are returned as PyTorch tensors. Together with the frame number, they provide the information recorded in the supplied CSV.</p>
<p>Try changing <code>frame_number</code> to 38 and rerunning from the frame-reading step onwards. Compare your predictions with the precomputed detections for frame 38, remembering that our plot only shows boxes with confidence <span class="math inline">\(\ge 0.50\)</span>.</p>
<p>For the full-video analysis, we will use the supplied CSV so that everyone works with the same predictions. You do not need to rerun the detector on the entire clip.</p>
</section>
<section id="annotating-the-videos" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="annotating-the-videos"><span class="header-section-number">3.5</span> Annotating the videos</h2>
<p>If you would like to explore annotating the videos yourself, <a href="https://www.makesense.ai/"><strong>Make Sense</strong></a> is a free, <a href="https://github.com/SkalskiP/make-sense">open-source</a> image-annotation tool that runs in your browser. It was created by <a href="https://github.com/SkalskiP">Piotr Skalski</a>, who works at the computer-vision company <a href="https://roboflow.com/">Roboflow</a>. Many other annotation tools are available; here we use Make Sense for a simple, quick exercise on one frame rather than the full video. This is optional exploration; we will use the supplied annotations for the main analysis.</p>
<p>Start by <a href="attachments/trackid3x3-s1t4/frame50_raw.png" download="frame50_raw.png">downloading the unannotated frame-50 PNG</a>, then:</p>
<ol type="1">
<li>Open Make Sense, select <strong>Get Started</strong>, and load the PNG for <strong>Object Detection</strong>.</li>
<li>In <strong>Create labels</strong>, use <strong>+</strong> to add one label called <code>player</code>, then choose <strong>Start project</strong>.</li>
<li>Use the rectangle tool to draw boxes around the six active players, excluding the other people in the image. For each box, choose <strong>Select label → player</strong> in the right-hand panel.</li>
<li>Compare your boxes with <a href="#fig-dataset-frame50-annotations" class="quarto-xref">Figure&nbsp;<span>3.2</span></a>. Did you make the same choices about where the boxes begin and end?</li>
<li>Choose <strong>Actions → Export Annotations</strong>, select <strong>Single CSV file</strong>, then click <strong>Export</strong> to download your annotations. Save your work before closing the tab.</li>
</ol>
<p>Use manual annotation for this exercise; leave AI-server integrations off. No API key is needed.</p>
<p>To annotate another frame, change <code>frame_number</code> in the earlier frame-reading code and rerun that cell. Then save the unannotated image as a PNG:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>cv2.imwrite(<span class="ss">f"frame</span><span class="sc">{</span>frame_number<span class="sc">}</span><span class="ss">_raw.png"</span>, frame_bgr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>If using Colab, download the saved PNG from the Files pane before loading it into Make Sense. You do not need to run the detector to create this image.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./basketball_application.html" class="pagination-link  aria-label=" &lt;span="" from="" amateur="" basketball="" video="" footage="" to="" player="" trajectories&lt;="" span&gt;"="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Application: From amateur basketball video footage to player trajectories</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./camera_models.html" class="pagination-link" aria-label="<span class='chapter-number'>4</span>&nbsp; <span class='chapter-title'>Camera models</span>">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Camera models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb10" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Obtaining and visualising the dataset</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>As mentioned, there is a curated version of the dataset for this application provided on Canvas. However, if you would like to obtain the original dataset, you can find it in the <span class="co">[</span><span class="ot">TrackID3x3 public data archive</span><span class="co">](https://drive.google.com/drive/folders/1aWqMwQKr5xKMjqms7-raYluSlxPsGvwX)</span>.</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>Once you have obtained the course dataset you should explore it to understand its structure and contents. Some example explorations are given below. We use some terminology in what follows that you may not be familiar with, though it is hopefully clear from the context; we give more details on this terminology in the next section.</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="fu">## View the videos</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>Open <span class="in">`basket_S1T4_pre.mp4`</span> from the course dataset and watch the clip. It is about seven seconds long and was recorded with a fixed camera. Notice the six active players, as well as the other people visible around the court. Our task is to track the six active players, rather than every person in the image. A representative frame is shown below.</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="al">![Frame 50 of `basket_S1T4_pre`.](&lt;attachments/trackid3x3-s1t4/frame50_raw.png&gt;)</span>{#fig-dataset-frame50-raw width=100%}</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="fu">## View the annotations</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>The video comes with human-reviewed **annotations** marking the six active players. Each annotation contains a rectangular **bounding box** around a player and an anonymous **player ID**. Within this clip, the same ID refers to the same player across frames. These IDs are part of the supplied annotations.</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="al">![Annotation boxes with anonymous player IDs.](&lt;attachments/trackid3x3-s1t4/frame50_annotations.png&gt;)</span>{#fig-dataset-frame50-annotations width=100%}</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>The file <span class="in">`ground_truth_mot.txt`</span> contains these annotations as comma-separated rows, with one row per player per frame. In statistics terminology, rows represent our **unit of observation**, here a ‘player-and–frame’ combination, and these observations are arranged in a **long** format data table. Note that **ground truth** is the conventional name for manual/human-checked annotations even though human annotations may in fact contain errors! Here are three of the six rows for frame 50, with some column names added and unused columns omitted:</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>| <span class="in">`frame`</span> | <span class="in">`track_id`</span> | <span class="in">`x_left`</span> | <span class="in">`y_top`</span> | <span class="in">`width`</span> | <span class="in">`height`</span> |</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>|---:|---:|---:|---:|---:|---:|</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>| 50 | 1 | 529.00 | 414.00 | 82.00 | 143.00 |</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>| 50 | 2 | 975.70 | 415.64 | 81.93 | 166.28 |</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>| 50 | 3 | 333.92 | 310.58 | 30.47 | 89.20 |</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`frame`</span> identifies the video frame, numbered from 1.</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`track_id`</span> identifies the player within this clip.</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`x_left`</span> and <span class="in">`y_top`</span> give the image coordinates of the box's upper-left corner, in pixels.</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`width`</span> and <span class="in">`height`</span> give the box dimensions, also in pixels.</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>Image coordinates start at the upper-left corner: $x$ increases to the right and $y$ increases downwards. For example, the first row describes player 1 in frame 50. Its box starts at $(529, 414)$ and extends 82 pixels to the right and 143 pixels down, ending at $(611, 557)$.</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a><span class="al">![Coordinates and dimensions of the annotation box for player 1 in frame 50.](&lt;attachments/trackid3x3-s1t4/frame50_box_coordinates.png&gt;)</span>{#fig-dataset-box-coordinates width=85% fig-alt="Image coordinates increase rightwards and downwards. The box starts at (529, 414), is 82 pixels wide and 143 pixels high, and ends at (611, 557)."}</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a><span class="fu">## View the precomputed detections</span></span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>We have also (separately to the original dataset) provided **object detections**, or **predicted boxes**, produced by [**YOLO11n**](https://docs.ultralytics.com/models/yolo11/), a model developed by the computer-vision software company Ultralytics. This is a **pretrained object detector**: its parameters were learned from other images before we used it to analyse this clip. Here we ask it to **detect objects in the generic `person` category**. Importantly, this is *not the same as detecting players*, which is our application or engineering target. We will return to how these models work and are trained in the <span class="co">[</span><span class="ot">object-detection chapter</span><span class="co">](object_detection.qmd)</span>.</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>Each predicted box comes with a **confidence score**, ranging from 0 to 1. Higher scores indicate stronger model support for a detection, but these are not necessarily calibrated probabilities of correctness on our task. We typically then use a **confidence threshold** to select which predictions to keep, e.g. 'keep only predictions with confidence $\ge 0.50$'. Of course, a high score does not guarantee that a prediction is correct or relevant to our task, and we need to evaluate the model's performance on our task.</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>The file <span class="in">`yolo11n_person_conf001.csv`</span> contains the detector library's saved predictions, produced using a low confidence threshold of 0.01, in order to save as many predictions as possible. Each row contains a predicted box, *here in terms of the upper-left corner and lower-right corner rather than upper-left corner and width/height*, plus a <span class="in">`confidence`</span> column.  For the illustration below, we keep only predictions with confidence $\ge 0.50$, leaving eight of the 31 saved predictions for frame 50. At this stage we filter only by confidence, not by any other criteria which might distinguish players from non-players.</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a><span class="al">![YOLO11n predicted boxes, labelled by confidence ($\ge 0.50$).](&lt;attachments/trackid3x3-s1t4/frame50_predictions_conf050.png&gt;)</span>{#fig-dataset-frame50-predictions width=100%}</span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>Notice that the model also detects non-players, e.g. an apparent coach or similar figure standing near the sideline and two observers sitting at mid court. In fact, for the two sitting observers the model only detects one of them, and the other is missed, presumably because they are sitting very close together.</span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a>Here are the three highest-confidence predictions for this frame, with scores and coordinates rounded to two decimal places:</span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a>| <span class="in">`frame`</span> | <span class="in">`confidence`</span> | <span class="in">`x_min`</span> | <span class="in">`y_min`</span> | <span class="in">`x_max`</span> | <span class="in">`y_max`</span> |</span>
<span id="cb10-50"><a href="#cb10-50" aria-hidden="true" tabindex="-1"></a>|---:|---:|---:|---:|---:|---:|</span>
<span id="cb10-51"><a href="#cb10-51" aria-hidden="true" tabindex="-1"></a>| 50 | 0.85 | 1018.13 | 509.92 | 1123.76 | 719.90 |</span>
<span id="cb10-52"><a href="#cb10-52" aria-hidden="true" tabindex="-1"></a>| 50 | 0.83 | 332.86 | 310.63 | 363.40 | 396.43 |</span>
<span id="cb10-53"><a href="#cb10-53" aria-hidden="true" tabindex="-1"></a>| 50 | 0.79 | 528.20 | 415.57 | 608.95 | 551.22 |</span>
<span id="cb10-54"><a href="#cb10-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-55"><a href="#cb10-55" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`frame`</span> identifies the video frame, as before.</span>
<span id="cb10-56"><a href="#cb10-56" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`confidence`</span> is the score assigned to the predicted box, not a player ID.</span>
<span id="cb10-57"><a href="#cb10-57" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`x_min`</span> and <span class="in">`y_min`</span> give the upper-left corner of the box.</span>
<span id="cb10-58"><a href="#cb10-58" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`x_max`</span> and <span class="in">`y_max`</span> give the lower-right corner of the box.</span>
<span id="cb10-59"><a href="#cb10-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-60"><a href="#cb10-60" aria-hidden="true" tabindex="-1"></a>These coordinates are in pixels. Since the boxes are given in terms of the upper-left and lower-right corners, we can compute the width and height of the box as <span class="in">`width = x_max - x_min`</span> and <span class="in">`height = y_max - y_min`</span> for comparison with the annotation boxes.</span>
<span id="cb10-61"><a href="#cb10-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-62"><a href="#cb10-62" aria-hidden="true" tabindex="-1"></a>There is no <span class="in">`track_id`</span> column here, and the rows have not been matched to the annotation rows above. **A key task will be to compare the predicted boxes with the annotations** and hence evaluate the detector. Later, we will link predictions across frames to carry out the tracking task.</span>
<span id="cb10-63"><a href="#cb10-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-64"><a href="#cb10-64" aria-hidden="true" tabindex="-1"></a><span class="fu">## Generate your own detections</span></span>
<span id="cb10-65"><a href="#cb10-65" aria-hidden="true" tabindex="-1"></a>We can generate our own detections using the <span class="in">`ultralytics`</span> Python package. Here we use the pretrained YOLO11n model to perform **inference**: given an image, it returns predicted boxes, class labels and confidence scores, without changing its learned parameters. We will start with frame 50 of our video, so that we can compare the output with the precomputed detections above.</span>
<span id="cb10-66"><a href="#cb10-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-67"><a href="#cb10-67" aria-hidden="true" tabindex="-1"></a>We can run this example in a Jupyter notebook on our own machine or in Google Colab. Since we are only running the pretrained model on a single frame, a GPU is not required. If using Colab, upload <span class="in">`basket_S1T4_pre.mp4`</span> directly through the Files pane on the left; there is no need to mount Google Drive.</span>
<span id="cb10-68"><a href="#cb10-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-69"><a href="#cb10-69" aria-hidden="true" tabindex="-1"></a>First, install the <span class="in">`ultralytics`</span> package in the notebook. We specify the version used to generate the supplied detections:</span>
<span id="cb10-70"><a href="#cb10-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-71"><a href="#cb10-71" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb10-72"><a href="#cb10-72" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>pip install ultralytics<span class="op">==</span><span class="fl">8.4.52</span></span>
<span id="cb10-73"><a href="#cb10-73" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-74"><a href="#cb10-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-75"><a href="#cb10-75" aria-hidden="true" tabindex="-1"></a>Then import <span class="in">`YOLO`</span> and load the pretrained model:</span>
<span id="cb10-76"><a href="#cb10-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-77"><a href="#cb10-77" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb10-78"><a href="#cb10-78" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ultralytics <span class="im">import</span> YOLO</span>
<span id="cb10-79"><a href="#cb10-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-80"><a href="#cb10-80" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> YOLO(<span class="st">"yolo11n.pt"</span>)</span>
<span id="cb10-81"><a href="#cb10-81" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-82"><a href="#cb10-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-83"><a href="#cb10-83" aria-hidden="true" tabindex="-1"></a>The <span class="in">`.pt`</span> extension is a common convention for files saved by **PyTorch**, the deep-learning library used by <span class="in">`ultralytics`</span>. Saving a model records its learned parameters so that they can be reused without retraining. Loading restores these parameters into the corresponding model structure; here, the <span class="in">`YOLO`</span> interface handles this for us. The library downloads <span class="in">`yolo11n.pt`</span> automatically if needed, so the first run requires internet access. This loads the model; it does not yet run detection on an image.</span>
<span id="cb10-84"><a href="#cb10-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-85"><a href="#cb10-85" aria-hidden="true" tabindex="-1"></a>We use **OpenCV**, a library for working with images and video, to read the frame. Here we assume the video file is in the notebook’s working directory. Our dataset numbers frames from 1, whereas OpenCV uses indices starting from 0, so frame 50 has index 49.</span>
<span id="cb10-86"><a href="#cb10-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-87"><a href="#cb10-87" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb10-88"><a href="#cb10-88" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cv2</span>
<span id="cb10-89"><a href="#cb10-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-90"><a href="#cb10-90" aria-hidden="true" tabindex="-1"></a>frame_number <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb10-91"><a href="#cb10-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-92"><a href="#cb10-92" aria-hidden="true" tabindex="-1"></a>video <span class="op">=</span> cv2.VideoCapture(<span class="st">"basket_S1T4_pre.mp4"</span>)</span>
<span id="cb10-93"><a href="#cb10-93" aria-hidden="true" tabindex="-1"></a>video.<span class="bu">set</span>(cv2.CAP_PROP_POS_FRAMES, frame_number <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb10-94"><a href="#cb10-94" aria-hidden="true" tabindex="-1"></a>success, frame_bgr <span class="op">=</span> video.read()</span>
<span id="cb10-95"><a href="#cb10-95" aria-hidden="true" tabindex="-1"></a>video.release()</span>
<span id="cb10-96"><a href="#cb10-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-97"><a href="#cb10-97" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> success:</span>
<span id="cb10-98"><a href="#cb10-98" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">RuntimeError</span>(</span>
<span id="cb10-99"><a href="#cb10-99" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"Could not read frame </span><span class="sc">{</span>frame_number<span class="sc">}</span><span class="ss">. Check the video file path."</span></span>
<span id="cb10-100"><a href="#cb10-100" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb10-101"><a href="#cb10-101" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-102"><a href="#cb10-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-103"><a href="#cb10-103" aria-hidden="true" tabindex="-1"></a>The image is now stored in the NumPy array <span class="in">`frame_bgr`</span>. OpenCV stores its colour channels in blue–green–red (BGR) order, which we will account for when displaying it.</span>
<span id="cb10-104"><a href="#cb10-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-105"><a href="#cb10-105" aria-hidden="true" tabindex="-1"></a>Matplotlib expects colour channels in RGB order, so we make a separate RGB array for display:</span>
<span id="cb10-106"><a href="#cb10-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-107"><a href="#cb10-107" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb10-108"><a href="#cb10-108" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb10-109"><a href="#cb10-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-110"><a href="#cb10-110" aria-hidden="true" tabindex="-1"></a>frame_rgb <span class="op">=</span> cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)</span>
<span id="cb10-111"><a href="#cb10-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-112"><a href="#cb10-112" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb10-113"><a href="#cb10-113" aria-hidden="true" tabindex="-1"></a>plt.imshow(frame_rgb)</span>
<span id="cb10-114"><a href="#cb10-114" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">"off"</span>)</span>
<span id="cb10-115"><a href="#cb10-115" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb10-116"><a href="#cb10-116" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-117"><a href="#cb10-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-118"><a href="#cb10-118" aria-hidden="true" tabindex="-1"></a>With <span class="in">`frame_number = 50`</span>, this should show the same unannotated frame displayed earlier. We keep <span class="in">`frame_bgr`</span> for the next step: YOLO expects BGR channel order when we pass it a NumPy array.</span>
<span id="cb10-119"><a href="#cb10-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-120"><a href="#cb10-120" aria-hidden="true" tabindex="-1"></a>This pretrained model is trained to recognise 80 object categories. The dictionary <span class="in">`model.names`</span> maps each category’s ID to its name. We can display them all with:</span>
<span id="cb10-121"><a href="#cb10-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-122"><a href="#cb10-122" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb10-123"><a href="#cb10-123" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> class_id, class_name <span class="kw">in</span> model.names.items():</span>
<span id="cb10-124"><a href="#cb10-124" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(class_id, class_name)</span>
<span id="cb10-125"><a href="#cb10-125" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-126"><a href="#cb10-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-127"><a href="#cb10-127" aria-hidden="true" tabindex="-1"></a>Examples include <span class="in">`0: person`</span>, <span class="in">`1: bicycle`</span>, <span class="in">`2: car`</span> and <span class="in">`16: dog`</span>. These are category IDs, not identifiers for individual objects. We use <span class="in">`classes=[0]`</span> to keep only person detections. For example, <span class="in">`classes=[0, 2]`</span> would keep person and car detections, while omitting the <span class="in">`classes`</span> argument allows predictions from any of the model’s categories.</span>
<span id="cb10-128"><a href="#cb10-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-129"><a href="#cb10-129" aria-hidden="true" tabindex="-1"></a>We can now pass the frame to the detector. We request only <span class="in">`person`</span> detections and use the same low confidence threshold as the supplied CSV, leaving stricter filtering until afterwards:</span>
<span id="cb10-130"><a href="#cb10-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-131"><a href="#cb10-131" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb10-132"><a href="#cb10-132" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> model.predict(</span>
<span id="cb10-133"><a href="#cb10-133" aria-hidden="true" tabindex="-1"></a>    source<span class="op">=</span>frame_bgr,</span>
<span id="cb10-134"><a href="#cb10-134" aria-hidden="true" tabindex="-1"></a>    classes<span class="op">=</span>[<span class="dv">0</span>],</span>
<span id="cb10-135"><a href="#cb10-135" aria-hidden="true" tabindex="-1"></a>    conf<span class="op">=</span><span class="fl">0.01</span>,</span>
<span id="cb10-136"><a href="#cb10-136" aria-hidden="true" tabindex="-1"></a>    iou<span class="op">=</span><span class="fl">0.70</span>,</span>
<span id="cb10-137"><a href="#cb10-137" aria-hidden="true" tabindex="-1"></a>    device<span class="op">=</span><span class="st">"cpu"</span>,</span>
<span id="cb10-138"><a href="#cb10-138" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-139"><a href="#cb10-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-140"><a href="#cb10-140" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> results[<span class="dv">0</span>]</span>
<span id="cb10-141"><a href="#cb10-141" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-142"><a href="#cb10-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-143"><a href="#cb10-143" aria-hidden="true" tabindex="-1"></a>Here <span class="in">`classes=[0]`</span> selects the model’s <span class="in">`person`</span> category—not a player ID. The <span class="in">`iou`</span> setting controls suppression of strongly overlapping predicted boxes, which we will discuss later. It does not compare predictions with our annotations.</span>
<span id="cb10-144"><a href="#cb10-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-145"><a href="#cb10-145" aria-hidden="true" tabindex="-1"></a>The <span class="in">`predict`</span> method returns a list containing one result per input image. Since we supplied one frame, <span class="in">`results[0]`</span> gives us its result.</span>
<span id="cb10-146"><a href="#cb10-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-147"><a href="#cb10-147" aria-hidden="true" tabindex="-1"></a><span class="in">`result.boxes.conf`</span> contains a confidence score for each predicted box. We select the higher-confidence predictions for display, leaving the original <span class="in">`result`</span> unchanged:</span>
<span id="cb10-148"><a href="#cb10-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-149"><a href="#cb10-149" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb10-150"><a href="#cb10-150" aria-hidden="true" tabindex="-1"></a>keep <span class="op">=</span> result.boxes.conf <span class="op">&gt;=</span> <span class="fl">0.50</span></span>
<span id="cb10-151"><a href="#cb10-151" aria-hidden="true" tabindex="-1"></a>display_result <span class="op">=</span> result[keep]</span>
<span id="cb10-152"><a href="#cb10-152" aria-hidden="true" tabindex="-1"></a>prediction_image_bgr <span class="op">=</span> display_result.plot()</span>
<span id="cb10-153"><a href="#cb10-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-154"><a href="#cb10-154" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb10-155"><a href="#cb10-155" aria-hidden="true" tabindex="-1"></a>plt.imshow(cv2.cvtColor(prediction_image_bgr, cv2.COLOR_BGR2RGB))</span>
<span id="cb10-156"><a href="#cb10-156" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">"off"</span>)</span>
<span id="cb10-157"><a href="#cb10-157" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb10-158"><a href="#cb10-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-159"><a href="#cb10-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-160"><a href="#cb10-160" aria-hidden="true" tabindex="-1"></a>The <span class="in">`plot()`</span> method returns an image with the predicted boxes and labels drawn on it, again in BGR order. The labels show the predicted category and confidence, not a player ID.</span>
<span id="cb10-161"><a href="#cb10-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-162"><a href="#cb10-162" aria-hidden="true" tabindex="-1"></a>We can inspect the predicted box coordinates and confidence scores directly. For example, the following prints the first three predictions:</span>
<span id="cb10-163"><a href="#cb10-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-164"><a href="#cb10-164" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb10-165"><a href="#cb10-165" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(result.boxes.xyxy[:<span class="dv">3</span>])</span>
<span id="cb10-166"><a href="#cb10-166" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(result.boxes.conf[:<span class="dv">3</span>])</span>
<span id="cb10-167"><a href="#cb10-167" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-168"><a href="#cb10-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-169"><a href="#cb10-169" aria-hidden="true" tabindex="-1"></a>Each row of <span class="in">`xyxy`</span> contains <span class="in">`[x_min, y_min, x_max, y_max]`</span> in pixels. The corresponding entry in <span class="in">`conf`</span> gives that box’s confidence score. These values are returned as PyTorch tensors. Together with the frame number, they provide the information recorded in the supplied CSV.</span>
<span id="cb10-170"><a href="#cb10-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-171"><a href="#cb10-171" aria-hidden="true" tabindex="-1"></a>Try changing <span class="in">`frame_number`</span> to 38 and rerunning from the frame-reading step onwards. Compare your predictions with the precomputed detections for frame 38, remembering that our plot only shows boxes with confidence $\ge 0.50$.</span>
<span id="cb10-172"><a href="#cb10-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-173"><a href="#cb10-173" aria-hidden="true" tabindex="-1"></a>For the full-video analysis, we will use the supplied CSV so that everyone works with the same predictions. You do not need to rerun the detector on the entire clip.</span>
<span id="cb10-174"><a href="#cb10-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-175"><a href="#cb10-175" aria-hidden="true" tabindex="-1"></a><span class="fu">## Annotating the videos</span></span>
<span id="cb10-176"><a href="#cb10-176" aria-hidden="true" tabindex="-1"></a>If you would like to explore annotating the videos yourself, <span class="co">[</span><span class="ot">**Make Sense**</span><span class="co">](https://www.makesense.ai/)</span> is a free, <span class="co">[</span><span class="ot">open-source</span><span class="co">](https://github.com/SkalskiP/make-sense)</span> image-annotation tool that runs in your browser. It was created by <span class="co">[</span><span class="ot">Piotr Skalski</span><span class="co">](https://github.com/SkalskiP)</span>, who works at the computer-vision company <span class="co">[</span><span class="ot">Roboflow</span><span class="co">](https://roboflow.com/)</span>. Many other annotation tools are available; here we use Make Sense for a simple, quick exercise on one frame rather than the full video. This is optional exploration; we will use the supplied annotations for the main analysis.</span>
<span id="cb10-177"><a href="#cb10-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-178"><a href="#cb10-178" aria-hidden="true" tabindex="-1"></a>Start by <span class="co">[</span><span class="ot">downloading the unannotated frame-50 PNG</span><span class="co">](&lt;attachments/trackid3x3-s1t4/frame50_raw.png&gt;)</span>{download="frame50_raw.png"}, then:</span>
<span id="cb10-179"><a href="#cb10-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-180"><a href="#cb10-180" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Open Make Sense, select **Get Started**, and load the PNG for **Object Detection**.</span>
<span id="cb10-181"><a href="#cb10-181" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>In **Create labels**, use **+** to add one label called `player`, then choose **Start project**.</span>
<span id="cb10-182"><a href="#cb10-182" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Use the rectangle tool to draw boxes around the six active players, excluding the other people in the image. For each box, choose **Select label → player** in the right-hand panel.</span>
<span id="cb10-183"><a href="#cb10-183" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Compare your boxes with @fig-dataset-frame50-annotations. Did you make the same choices about where the boxes begin and end?</span>
<span id="cb10-184"><a href="#cb10-184" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Choose **Actions → Export Annotations**, select **Single CSV file**, then click **Export** to download your annotations. Save your work before closing the tab.</span>
<span id="cb10-185"><a href="#cb10-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-186"><a href="#cb10-186" aria-hidden="true" tabindex="-1"></a>Use manual annotation for this exercise; leave AI-server integrations off. No API key is needed.</span>
<span id="cb10-187"><a href="#cb10-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-188"><a href="#cb10-188" aria-hidden="true" tabindex="-1"></a>To annotate another frame, change <span class="in">`frame_number`</span> in the earlier frame-reading code and rerun that cell. Then save the unannotated image as a PNG:</span>
<span id="cb10-189"><a href="#cb10-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-190"><a href="#cb10-190" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb10-191"><a href="#cb10-191" aria-hidden="true" tabindex="-1"></a>cv2.imwrite(<span class="ss">f"frame</span><span class="sc">{</span>frame_number<span class="sc">}</span><span class="ss">_raw.png"</span>, frame_bgr)</span>
<span id="cb10-192"><a href="#cb10-192" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb10-193"><a href="#cb10-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-194"><a href="#cb10-194" aria-hidden="true" tabindex="-1"></a>If using Colab, download the saved PNG from the Files pane before loading it into Make Sense. You do not need to run the detector to create this image.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><a href="attribution.txt">Third-party sources and licences</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>