<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ENGSCI 304: Engineering Machine Learning II - 13&nbsp; Filtering and practical trackers</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./tracking_evaluation.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/print.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./visual.html">Visual data</a></li><li class="breadcrumb-item"><a href="./tracking_filtering.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Filtering and practical trackers</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ENGSCI 304: Engineering Machine Learning II</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About these notes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recommended_reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Recommended reading</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./visual.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visual data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basketball_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Application: From amateur basketball video footage to player trajectories</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dataset.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Obtaining and visualising the dataset</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./camera_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Camera models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./image_tasks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Image analysis tasks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./image_modelling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Image modelling: From pixels to learned features</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./training.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Training and inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./object_detection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Object detection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Evaluation of detection models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tracking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Basic tracking</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tracking_motion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Motion-based tracking</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tracking_evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Evaluating tracks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tracking_filtering.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Filtering and practical trackers</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#filtering-the-motion-estimates" id="toc-filtering-the-motion-estimates" class="nav-link active" data-scroll-target="#filtering-the-motion-estimates"><span class="header-section-number">13.1</span> Filtering the motion estimates</a></li>
  <li><a href="#filtering-the-basketball-tracks" id="toc-filtering-the-basketball-tracks" class="nav-link" data-scroll-target="#filtering-the-basketball-tracks"><span class="header-section-number">13.2</span> Filtering the basketball tracks</a>
  <ul class="collapse">
  <li><a href="#scores-for-frames-50100" id="toc-scores-for-frames-50100" class="nav-link" data-scroll-target="#scores-for-frames-50100"><span class="header-section-number">13.2.1</span> Scores for frames 50–100</a></li>
  <li><a href="#restarting-over-the-full-clip" id="toc-restarting-over-the-full-clip" class="nav-link" data-scroll-target="#restarting-over-the-full-clip"><span class="header-section-number">13.2.2</span> Restarting over the full clip</a></li>
  </ul></li>
  <li><a href="#practical-trackers-and-appearance-information" id="toc-practical-trackers-and-appearance-information" class="nav-link" data-scroll-target="#practical-trackers-and-appearance-information"><span class="header-section-number">13.3</span> Practical trackers and appearance information</a>
  <ul class="collapse">
  <li><a href="#using-confidence-differently-for-updates-and-new-tracks" id="toc-using-confidence-differently-for-updates-and-new-tracks" class="nav-link" data-scroll-target="#using-confidence-differently-for-updates-and-new-tracks"><span class="header-section-number">13.3.1</span> Using confidence differently for updates and new tracks</a></li>
  <li><a href="#using-the-image-inside-the-box" id="toc-using-the-image-inside-the-box" class="nav-link" data-scroll-target="#using-the-image-inside-the-box"><span class="header-section-number">13.3.2</span> Using the image inside the box</a></li>
  </ul></li>
  <li><a href="#modern-directions-promptable-video-segmentation" id="toc-modern-directions-promptable-video-segmentation" class="nav-link" data-scroll-target="#modern-directions-promptable-video-segmentation"><span class="header-section-number">13.4</span> Modern directions: promptable video segmentation</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./visual.html">Visual data</a></li><li class="breadcrumb-item"><a href="./tracking_filtering.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Filtering and practical trackers</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Filtering and practical trackers</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>We now return to improving the tracker, first by filtering the motion estimates and then by looking at how practical trackers use detection confidence, appearance and prompts.</p>
<section id="filtering-the-motion-estimates" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="filtering-the-motion-estimates"><span class="header-section-number">13.1</span> Filtering the motion estimates</h2>
<p>Our current motion predictor estimates velocity from the two most recent detections. Errors in their positions therefore also affect the velocity estimate, which we then use to predict the next position.</p>
<p>For a simple example, suppose an object moves horizontally by 4 pixels per frame. Its true centre positions in four consecutive frames are 20, 24, 28 and 32 pixels. Suppose the first two detections give the correct positions, but the third gives 40 instead of 28. Our estimated velocity is then</p>
<p><span class="math display">\[
v = 40 - 24 = 16\quad\text{pixels per frame},
\]</span></p>
<p>and the predicted position in the fourth frame is</p>
<p><span class="math display">\[
x_{\mathrm{predicted}} = 40 + 16 = 56\quad\text{pixels}.
\]</span></p>
<p>The true position is 32 pixels. The error in the third detection affects both the position from which we predict and the velocity used in that prediction.</p>
<p>A <strong>filter</strong>, in the context of state estimation and tracking, combines a motion prediction with a new observation to update our estimate of the object’s state (true position and velocity).</p>
<p>In the present application, we predict the object’s position in the new frame based on earlier frames, and the centre of a detected bounding box in the new frame is treated as a new noisy measurement of the current position. We then aim to combine the predicted and detected positions to obtain a new position state estimate for the current frame.</p>
<p>As a simple example, for one position coordinate, we can combine the predicted and detected positions using a weighted average:</p>
<p><span class="math display">\[
x_{\mathrm{updated}}
= (1-k)x_{\mathrm{predicted}} + kx_{\mathrm{detected}},
\qquad 0\leq k\leq 1.
\]</span></p>
<p>Here <span class="math inline">\(k\)</span> controls how much weight we give the new detection. A value close to 1 puts most of the weight on the detected position, while a value close to 0 puts most of the weight on the prediction. Equivalently,</p>
<p><span class="math display">\[
x_{\mathrm{updated}}
= x_{\mathrm{predicted}}
+ k\bigl(x_{\mathrm{detected}}-x_{\mathrm{predicted}}\bigr).
\]</span></p>
<p>Thus we see the idea is to form the update as a corrected prediction, based on the difference between the predicted and detected positions. The degree to which we weight the prediction or the new observation needs to be determined.</p>
<p>A <strong>Kalman filter</strong> uses estimates of uncertainty to determine these correction weights. A more uncertain observation receives less weight relative to the prediction; a more uncertain prediction receives less weight relative to the observation. The filter combines the motion model with an <strong>observation model</strong> describing errors in the detected positions. It updates the velocity estimate as well: an error in velocity produces a position error during prediction, so the position discrepancy also provides information about velocity. We will not describe Kalman filters in detail here, but they are used in the <a href="https://doi.org/10.1109/ICIP.2016.7533003">SORT tracking algorithm</a> and are widely used in navigation and control systems more generally.</p>
<p>If we take this approach, our tracking loop now also carries filtered estimates of position and velocity for each track. Given a new frame, we first use the previous estimates to predict the object’s next box and perform the same IoU-based matching to detections as before, using the (uncorrected) prediction and new detection. Once the new prediction–detection pair has been established, we carry out the filter’s correction step for the position and velocity estimates, in preparation for predicting the next frame. In this example, we keep the width and height of the latest observed box for the estimated box.</p>
<p>In terms of recording the results, we still record the actual detection alongside the current estimated position and velocity. Saving these observations and state estimates at each frame lets us compare the <strong>detection history</strong> with the <strong>estimated trajectory</strong> for the same track. When an active track has no assigned detection, its detection history has a gap, while the motion model provides a predicted position for that frame.</p>
</section>
<section id="filtering-the-basketball-tracks" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="filtering-the-basketball-tracks"><span class="header-section-number">13.2</span> Filtering the basketball tracks</h2>
<p>We can now repeat the basketball example using Kalman-filtered motion in place of the two-observation motion predictor. We again track frames 50–100 at confidence cutoff 0.40, keeping the court filter, tracking IoU threshold of 0.30 and three-miss inactivation rule the same. The filter’s correction weights depend on assumptions about measurement noise and changes in motion. Here we use fixed, illustrative noise settings that have not been calibrated to this video.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>At frame 64, T2 labels the red player and T4 the black player. With the two-observation predictor, these labels have been exchanged by frame 71 and remain exchanged at frame 74, as shown below. With filtering, T2 still labels the red player and T4 the black player at frame 74. The boxes shown below are the detections assigned to each track.</p>
<div id="fig-tracking-basketball-filtered-motion" class="quarto-figure quarto-figure-center quarto-float anchored" alt="At frame 64 both methods label the red player T2 and the black player T4. At frame 74 two-observation motion has exchanged them, labelling the black player T2 and the red player T4, while Kalman-filtered motion keeps T2 on the red player and T4 on the black player.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tracking-basketball-filtered-motion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="attachments/tracking/basketball-filtered-before-after.png" class="img-fluid figure-img" style="width:100.0%" alt="At frame 64 both methods label the red player T2 and the black player T4. At frame 74 two-observation motion has exchanged them, labelling the black player T2 and the red player T4, while Kalman-filtered motion keeps T2 on the red player and T4 on the black player.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tracking-basketball-filtered-motion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.1: Assigned detections at frames 64 and 74 using the two-observation motion predictor (top) and Kalman-filtered motion (bottom). T2 is shown in red and T4 in dark grey throughout; the labels name the player each track follows.
</figcaption>
</figure>
</div>
<p>At the original confidence cutoff of 0.50, last-box matching, the two-observation predictor and Kalman-filtered motion all show the earlier frame-74 identity error. At 0.40, last-box matching avoids this red/black exchange, but the black player’s ID has changed from T4 to T7. Filtering keeps both original IDs through this interaction, using the additional detections available at 0.40. These additional detections also include duplicate boxes, and all three methods still create temporary duplicate tracks.</p>
<section id="scores-for-frames-50100" class="level3" data-number="13.2.1">
<h3 data-number="13.2.1" class="anchored" data-anchor-id="scores-for-frames-50100"><span class="header-section-number">13.2.1</span> Scores for frames 50–100</h3>
<p>We can evaluate the filtered tracks over frames 50–100 using the same evaluation IoU threshold of 0.50 as before. At each confidence cutoff, all three methods record the same detections, so their detection precision and recall are unchanged. We evaluate the assigned detection boxes and track IDs, rather than the filtered position estimates.</p>
<div id="tracking-filtered-identity-scores" class="tracking-metric-visual filtered-identities">
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Confidence cutoff</th>
<th style="text-align: left;">Tracking method</th>
<th style="text-align: right;">Identity precision</th>
<th style="text-align: right;">Identity recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0.50</td>
<td style="text-align: left;">Last-box</td>
<td style="text-align: right;">0.852</td>
<td style="text-align: right;">0.827</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.50</td>
<td style="text-align: left;">Two-observation motion</td>
<td style="text-align: right;">0.852</td>
<td style="text-align: right;">0.827</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0.50</td>
<td style="text-align: left;">Kalman-filtered motion</td>
<td style="text-align: right;">0.852</td>
<td style="text-align: right;">0.827</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.40</td>
<td style="text-align: left;">Last-box</td>
<td style="text-align: right;">0.914</td>
<td style="text-align: right;">0.908</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0.40</td>
<td style="text-align: left;">Two-observation motion</td>
<td style="text-align: right;">0.862</td>
<td style="text-align: right;">0.856</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.40</td>
<td style="text-align: left;">Kalman-filtered motion</td>
<td style="text-align: right;"><strong>0.970</strong></td>
<td style="text-align: right;"><strong>0.964</strong></td>
</tr>
</tbody>
</table>
<p><span class="metric-key">Blue rows add Kalman-filtered motion. Bold marks the best value in each score column.</span></p>
</div>
<p>At cutoff 0.50, filtering gives the same identity scores as the other two methods. At 0.40, it gives 295 accepted identity matches, compared with 278 for last-box matching and 262 for two-observation motion. This gives identity precision <span class="math inline">\(295/304\approx 0.970\)</span> and identity recall <span class="math inline">\(295/306\approx 0.964\)</span>.</p>
<p>For this filtered run at 0.40, every accepted detection match also has the identity chosen by the sequence-wide pairing. Identity precision and recall therefore equal detection precision and recall. The scores remain below 1 because there are nine unmatched predicted boxes and eleven missed annotation boxes.</p>
<p>We can also add the filtered runs to the IDF1, MOTA and HOTA comparison. These scores again use the actual assigned detections from fresh frames 50–100 runs, not filtered position estimates. IDF1 and MOTA use evaluation IoU 0.50; HOTA is averaged over the 19 thresholds from 0.05 to 0.95.</p>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Confidence cutoff</th>
<th style="text-align: left;">Tracking method</th>
<th style="text-align: right;">IDF1</th>
<th style="text-align: right;">MOTA</th>
<th style="text-align: right;">HOTA</th>
<th style="text-align: right;">ID switches</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0.50</td>
<td style="text-align: left;">Last-box</td>
<td style="text-align: right;"><strong>0.8391</strong></td>
<td style="text-align: right;">0.9118</td>
<td style="text-align: right;">0.6758</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.50</td>
<td style="text-align: left;">Two-observation motion</td>
<td style="text-align: right;"><strong>0.8391</strong></td>
<td style="text-align: right;"><strong>0.9150</strong></td>
<td style="text-align: right;"><strong>0.6793</strong></td>
<td style="text-align: right;"><strong>3</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">0.50</td>
<td style="text-align: left;">Kalman-filtered motion</td>
<td style="text-align: right;"><strong>0.8391</strong></td>
<td style="text-align: right;"><strong>0.9150</strong></td>
<td style="text-align: right;"><strong>0.6793</strong></td>
<td style="text-align: right;"><strong>3</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">0.40</td>
<td style="text-align: left;">Last-box</td>
<td style="text-align: right;">0.9115</td>
<td style="text-align: right;">0.9314</td>
<td style="text-align: right;">0.7153</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0.40</td>
<td style="text-align: left;">Two-observation motion</td>
<td style="text-align: right;">0.8590</td>
<td style="text-align: right;">0.9248</td>
<td style="text-align: right;">0.6703</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.40</td>
<td style="text-align: left;">Kalman-filtered motion</td>
<td style="text-align: right;"><strong>0.9672</strong></td>
<td style="text-align: right;"><strong>0.9346</strong></td>
<td style="text-align: right;"><strong>0.7375</strong></td>
<td style="text-align: right;"><strong>0</strong></td>
</tr>
</tbody>
</table>
<p>Bold again marks the best values within each confidence group, including ties. The ID switches are counted by the same CLEAR evaluation used in MOTA.</p>
<p>At confidence cutoff 0.40, filtering gives the highest of these scores in this window, while two-observation motion scores below last-box.</p>
</section>
<section id="restarting-over-the-full-clip" class="level3" data-number="13.2.2">
<h3 data-number="13.2.2" class="anchored" data-anchor-id="restarting-over-the-full-clip"><span class="header-section-number">13.2.2</span> Restarting over the full clip</h3>
<p>The scores above describe runs that begin at frame 50 and end at frame 100. We now compare last-box matching and filtered motion over the full clip, frames 1–142, using confidence cutoff 0.40. Both trackers start afresh at frame 1, so their track IDs differ from those in the earlier example. In this run, T2 labels the orange-shirted player. At frame 116, a duplicate detection creates a second track, T12, for the same player.</p>
<div id="fig-tracking-basketball-filtering-failure119" class="quarto-figure quarto-figure-center quarto-float anchored" alt="Last-box matching (top) and Kalman-filtered motion (bottom) when duplicate detections create competing tracks.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tracking-basketball-filtering-failure119-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="attachments/tracking/basketball-filtering-failure119.png" class="img-fluid figure-img" style="width:100.0%" alt="Last-box matching (top) and Kalman-filtered motion (bottom) when duplicate detections create competing tracks.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tracking-basketball-filtering-failure119-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.2: Last-box matching (top) and Kalman-filtered motion (bottom) when duplicate detections create competing tracks.
</figcaption>
</figure>
</div>
<p>At frame 119, last-box matching keeps T2, while filtered motion assigns the detection to T12. The T2 reference box has IoU 0.776 with the detection under last-box matching, and 0.743 when predicted from the filtered state. The competing T12 reference has IoU 0.749 in both runs. All these overlaps are above the acceptance cutoff of 0.30, but the one-to-one assignment selects a different track in each case.</p>
<p>With the settings used here, adding Kalman filtering gives a local improvement in the assigned track IDs but no clear overall advantage over last-box matching across this short clip. Missing detections and competing tracks created by duplicate boxes still cause problems.</p>
<p>A clearer benefit can arise for an object moving a substantial distance between frames at roughly constant speed and direction, with noisy position measurements. The motion model predicts beyond the last observed box, while the filter combines observations over time to reduce the effect of individual detection errors on the position and velocity estimates.</p>
<p><em>Source images: <a href="https://doi.org/10.1145/3728423.3759400">TrackID3x3</a>, <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.</em></p>
</section>
</section>
<section id="practical-trackers-and-appearance-information" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="practical-trackers-and-appearance-information"><span class="header-section-number">13.3</span> Practical trackers and appearance information</h2>
<p>We have used three ways to form the reference box for matching a track to a new detection:</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Reference</th>
<th style="text-align: left;">How we form it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last observed box</td>
<td style="text-align: left;">Use the box from the most recent detection assigned to the track.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Two-observation motion</td>
<td style="text-align: left;">Estimate velocity from the two most recent observations and predict the next box.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kalman-filtered motion</td>
<td style="text-align: left;">Predict from position and velocity estimates that combine earlier predictions and observations.</td>
</tr>
</tbody>
</table>
<p>A complete tracker combines its motion model and matching method with rules for starting, confirming and ending tracks. The following methods illustrate different combinations of these ideas:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: left;">Main ideas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><a href="https://doi.org/10.1109/ICIP.2016.7533003">SORT</a></td>
<td style="text-align: left;">Kalman box prediction, IoU association and track management.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://doi.org/10.1109/ICIP.2017.8296962">Deep SORT</a></td>
<td style="text-align: left;">Kalman motion prediction and learned appearance information for association.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><a href="https://doi.org/10.1007/978-3-031-20047-2_1">ByteTrack</a></td>
<td style="text-align: left;">Kalman motion prediction; match high-confidence detections first, then use lower-confidence detections to update remaining active tracks.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="https://arxiv.org/abs/2206.14651">BoT-SORT</a></td>
<td style="text-align: left;">ByteTrack-style association with a revised box-motion model, camera-motion compensation and optional appearance matching.</td>
</tr>
</tbody>
</table>
<p>Our small filter-based tracker shares its basic structure with SORT, although SORT also models box size and has different track-confirmation and expiry rules. We can now consider two further sources of information used by these methods: detection confidence and appearance.</p>
<section id="using-confidence-differently-for-updates-and-new-tracks" class="level3" data-number="13.3.1">
<h3 data-number="13.3.1" class="anchored" data-anchor-id="using-confidence-differently-for-updates-and-new-tracks"><span class="header-section-number">13.3.1</span> Using confidence differently for updates and new tracks</h3>
<p>In our simple loop, an unmatched detection that passes the confidence cutoff starts a new track. ByteTrack separates the evidence needed to update a track from that needed to start one. It first matches high-confidence detections to existing tracks. It then tries lower-confidence detections against the remaining unmatched active tracks. These lower-confidence boxes can update those tracks, but cannot start new ones.</p>
<p>In our frames 50–100 test, the high threshold is 0.50 and the second stage uses scores between 0.10 and 0.50. It supplies six additional player observations compared with the same ByteTrack given only high-confidence inputs, including observations of the red and black players at frame 65. The benefit of this second stage is fewer gaps in the assigned detections.</p>
<p>At frame 73, the box with confidence about 0.69 updates T6. The overlapping box with confidence about 0.42 is unused: T6 has already been matched, and this lower-confidence box cannot start a new track. It therefore avoids the extra record created by our simple tracker at cutoff 0.40.</p>
<div id="fig-tracking-bytetrack-frame73" class="quarto-figure quarto-figure-center quarto-float anchored" alt="ByteTrack's supplied detections and assigned observation at frame 73.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tracking-bytetrack-frame73-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="attachments/tracking/bytetrack-frame73.png" class="img-fluid figure-img" style="width:100.0%" alt="ByteTrack's supplied detections and assigned observation at frame 73.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tracking-bytetrack-frame73-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.3: ByteTrack’s supplied detections and assigned observation at frame 73.
</figcaption>
</figure>
</div>
<p>Allowing weak observations can also affect later associations. In our full-clip test with high threshold 0.40, enabling the lower-confidence updates recovered additional observations but also produced more ID changes and duplicates than withholding those boxes.</p>
</section>
<section id="using-the-image-inside-the-box" class="level3" data-number="13.3.2">
<h3 data-number="13.3.2" class="anchored" data-anchor-id="using-the-image-inside-the-box"><span class="header-section-number">13.3.2</span> Using the image inside the box</h3>
<p>The image inside each box provides another source of information about which player it belongs to. A network trained for <strong>person re-identification (ReID)</strong> maps a cropped person image to a vector of features, or an <strong>appearance embedding</strong>. Its training encourages different images of the same person to have similar vectors. The tracker can compare a new crop with earlier crops assigned to a track, alongside its comparison of box positions.</p>
<p>We tested BoT-SORT with its appearance component switched off and on, keeping the other settings and supplied detections the same. Both runs cover frames 50–100 with high threshold 0.50. Camera-motion compensation is switched off for our fixed-camera video, and the appearance network is pretrained rather than trained on this basketball sequence.</p>
<p>At frame 71, both runs label the red player T2 and the black player T4. Both assign T4 to the red player at frame 73. With appearance enabled, the red player regains T2 at frame 74 and the black player regains T4 at frame 76. Without appearance, the red player remains T4 and the black player T2 through the rest of the run. The figure shows the assigned detection boxes.</p>
<div id="fig-tracking-botsort-appearance" class="quarto-figure quarto-figure-center quarto-float anchored" alt="BoT-SORT associations with appearance off (top) and on (bottom).">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tracking-botsort-appearance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="attachments/tracking/botsort-appearance.png" class="img-fluid figure-img" style="width:100.0%" alt="BoT-SORT associations with appearance off (top) and on (bottom).">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tracking-botsort-appearance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.4: BoT-SORT associations with appearance off (top) and on (bottom).
</figcaption>
</figure>
</div>
<p>Appearance can also favour a duplicate detection. In a run starting at frame 1 with the same high threshold of 0.50, the appearance-enabled tracker selects a lower-confidence duplicate at frame 27 because its crop is slightly more similar to the track’s stored appearance. The other, higher-confidence box then starts an additional track. Both crops depict the same player: appearance similarity alone does not select the better-localised box or prevent a duplicate record. The way the tracker combines appearance, confidence and track-management rules therefore still matters.</p>
<p><em>Source images: <a href="https://doi.org/10.1145/3728423.3759400">TrackID3x3</a>, <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.</em></p>
</section>
</section>
<section id="modern-directions-promptable-video-segmentation" class="level2" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="modern-directions-promptable-video-segmentation"><span class="header-section-number">13.4</span> Modern directions: promptable video segmentation</h2>
<p>In <a href="./image_tasks.html">Image analysis tasks</a>, we introduced <strong>instance segmentation</strong>, which identifies the pixels belonging to each separate object. This gives us a pixel mask for each player. We can also follow these masks through a video, keeping a consistent ID for each player.</p>
<p>Models such as <a href="https://ai.meta.com/research/sam3/"><strong>SAM 3</strong></a> support this kind of tracking. We can select an object using a <strong>box prompt</strong>: a rectangle indicating which object we want the model to segment and follow.</p>
<p>Here we use the <strong>six YOLO11n detections from frame 50 as initial box prompts</strong>. These are the same boxes retained by our confidence threshold of 0.50 and court filter. We give the selected objects IDs S1–S6, and SAM 3 predicts a mask for each one.</p>
<div id="fig-tracking-sam3-initial-prompts" class="quarto-figure quarto-figure-center quarto-float anchored" alt="Frame 50: the YOLO boxes on the left provide the initial prompts; SAM 3 predicts the masks on the right.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tracking-sam3-initial-prompts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="attachments/tracking/sam3-initial-prompts.png" class="img-fluid figure-img" style="width:100.0%" alt="Frame 50: the YOLO boxes on the left provide the initial prompts; SAM 3 predicts the masks on the right.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tracking-sam3-initial-prompts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.5: Frame 50: the YOLO boxes on the left provide the initial prompts; SAM 3 predicts the masks on the right. Source: TrackID3x3, CC BY 4.0; masks, overlays and layout added.
</figcaption>
</figure>
</div>
<p>After frame 50, we supply only the subsequent video frames, with no further YOLO detections or corrective prompts. SAM 3 uses each new image together with stored visual information from earlier frames to predict the six masks. In this example, it maintains the six identities through frame 100. The frames below show S2 and S4 remaining with the red- and black-shirted players as they overlap.</p>
<div id="fig-tracking-sam3-overlap" class="quarto-figure quarto-figure-center quarto-float anchored" alt="The two focal players retain their IDs through the overlap. S2 follows the player initially selected in the red shirt, and S4 follows the player in the black shirt.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tracking-sam3-overlap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="attachments/tracking/sam3-overlap.png" class="img-fluid figure-img" style="width:100.0%" alt="The two focal players retain their IDs through the overlap. S2 follows the player initially selected in the red shirt, and S4 follows the player in the black shirt.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tracking-sam3-overlap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.6: The two focal players retain their IDs through the overlap. S2 follows the player initially selected in the red shirt, and S4 follows the player in the black shirt. Source: TrackID3x3, CC BY 4.0; masks, crops, overlays and layout added.
</figcaption>
</figure>
</div>
<p><a href="attachments/tracking/sam3-50-100-slow.mp4">SAM 3 tracking the six players, shown in slow motion.</a></p>
<p>This is online tracking: each step uses the current image and information from earlier frames. However, real-time tracking also requires processing to keep up with the video. In the experiment we ran SAM3 processed the frames more slowly than they would arrive from a live camera so could not be used for real-time tracking.</p>
<p>Video and images: <a href="https://doi.org/10.1145/3728423.3759400">TrackID3x3</a>, <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.</p>


<!-- -->

</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Per image coordinate, we use a measurement-error standard deviation of 4 pixels and an acceleration-noise standard deviation of 1 pixel/frame². A new track starts with zero estimated velocity, position standard deviation 4 pixels and velocity standard deviation 10 pixels/frame.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./tracking_evaluation.html" class="pagination-link  aria-label=" &lt;span="" tracks&lt;="" span&gt;"="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Evaluating tracks</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Filtering and practical trackers</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>We now return to improving the tracker, first by filtering the motion estimates and then by looking at how practical trackers use detection confidence, appearance and prompts.</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">## Filtering the motion estimates</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>Our current motion predictor estimates velocity from the two most recent detections. Errors in their positions therefore also affect the velocity estimate, which we then use to predict the next position.</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>For a simple example, suppose an object moves horizontally by 4 pixels per frame. Its true centre positions in four consecutive frames are 20, 24, 28 and 32 pixels. Suppose the first two detections give the correct positions, but the third gives 40 instead of 28. Our estimated velocity is then</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>v = 40 - 24 = 16\quad\text{pixels per frame},</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>and the predicted position in the fourth frame is</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>x_{\mathrm{predicted}} = 40 + 16 = 56\quad\text{pixels}.</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>The true position is 32 pixels. The error in the third detection affects both the position from which we predict and the velocity used in that prediction.</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>A **filter**, in the context of state estimation and tracking, combines a motion prediction with a new observation to update our estimate of the object's state (true position and velocity).</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>In the present application, we predict the object's position in the new frame based on earlier frames, and the centre of a detected bounding box in the new frame is treated as a new noisy measurement of the current position. We then aim to combine the predicted and detected positions to obtain a new position state estimate for the current frame.</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>As a simple example, for one position coordinate, we can combine the predicted and detected positions using a weighted average:</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>x_{\mathrm{updated}}</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>= (1-k)x_{\mathrm{predicted}} + kx_{\mathrm{detected}},</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>\qquad 0\leq k\leq 1.</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>Here $k$ controls how much weight we give the new detection. A value close to 1 puts most of the weight on the detected position, while a value close to 0 puts most of the weight on the prediction. Equivalently,</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>x_{\mathrm{updated}}</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>= x_{\mathrm{predicted}}</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>k\bigl(x_{\mathrm{detected}}-x_{\mathrm{predicted}}\bigr).</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>Thus we see the idea is to form the update as a corrected prediction, based on the difference between the predicted and detected positions. The degree to which we weight the prediction or the new observation needs to be determined.</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>A **Kalman filter** uses estimates of uncertainty to determine these correction weights. A more uncertain observation receives less weight relative to the prediction; a more uncertain prediction receives less weight relative to the observation. The filter combines the motion model with an **observation model** describing errors in the detected positions. It updates the velocity estimate as well: an error in velocity produces a position error during prediction, so the position discrepancy also provides information about velocity. We will not describe Kalman filters in detail here, but they are used in the <span class="co">[</span><span class="ot">SORT tracking algorithm</span><span class="co">](https://doi.org/10.1109/ICIP.2016.7533003)</span> and are widely used in navigation and control systems more generally.</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>If we take this approach, our tracking loop now also carries filtered estimates of position and velocity for each track. Given a new frame, we first use the previous estimates to predict the object's next box and perform the same IoU-based matching to detections as before, using the (uncorrected) prediction and new detection. Once the new prediction–detection pair has been established, we carry out the filter's correction step for the position and velocity estimates, in preparation for predicting the next frame. In this example, we keep the width and height of the latest observed box for the estimated box.</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>In terms of recording the results, we still record the actual detection alongside the current estimated position and velocity. Saving these observations and state estimates at each frame lets us compare the **detection history** with the **estimated trajectory** for the same track. When an active track has no assigned detection, its detection history has a gap, while the motion model provides a predicted position for that frame.</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="fu">## Filtering the basketball tracks</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>We can now repeat the basketball example using Kalman-filtered motion in place of the two-observation motion predictor. We again track frames 50–100 at confidence cutoff 0.40, keeping the court filter, tracking IoU threshold of 0.30 and three-miss inactivation rule the same. The filter's correction weights depend on assumptions about measurement noise and changes in motion. Here we use fixed, illustrative noise settings that have not been calibrated to this video.<span class="ot">[^filter-noise]</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>At frame 64, T2 labels the red player and T4 the black player. With the two-observation predictor, these labels have been exchanged by frame 71 and remain exchanged at frame 74, as shown below. With filtering, T2 still labels the red player and T4 the black player at frame 74. The boxes shown below are the detections assigned to each track.</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="al">![Assigned detections at frames 64 and 74 using the two-observation motion predictor (top) and Kalman-filtered motion (bottom). T2 is shown in red and T4 in dark grey throughout; the labels name the player each track follows.](&lt;attachments/tracking/basketball-filtered-before-after.png&gt;)</span>{#fig-tracking-basketball-filtered-motion width=100% fig-alt="At frame 64 both methods label the red player T2 and the black player T4. At frame 74 two-observation motion has exchanged them, labelling the black player T2 and the red player T4, while Kalman-filtered motion keeps T2 on the red player and T4 on the black player."}</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>At the original confidence cutoff of 0.50, last-box matching, the two-observation predictor and Kalman-filtered motion all show the earlier frame-74 identity error. At 0.40, last-box matching avoids this red/black exchange, but the black player's ID has changed from T4 to T7. Filtering keeps both original IDs through this interaction, using the additional detections available at 0.40. These additional detections also include duplicate boxes, and all three methods still create temporary duplicate tracks.</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="fu">### Scores for frames 50–100</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>We can evaluate the filtered tracks over frames 50–100 using the same evaluation IoU threshold of 0.50 as before. At each confidence cutoff, all three methods record the same detections, so their detection precision and recall are unchanged. We evaluate the assigned detection boxes and track IDs, rather than the filtered position estimates.</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>::: {#tracking-filtered-identity-scores .tracking-metric-visual .filtered-identities}</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>| Confidence cutoff | Tracking method | Identity precision | Identity recall |</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>|:--|:--|--:|--:|</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>| 0.50 | Last-box | 0.852 | 0.827 |</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>| 0.50 | Two-observation motion | 0.852 | 0.827 |</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>| 0.50 | Kalman-filtered motion | 0.852 | 0.827 |</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>| 0.40 | Last-box | 0.914 | 0.908 |</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>| 0.40 | Two-observation motion | 0.862 | 0.856 |</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>| 0.40 | Kalman-filtered motion | **0.970** | **0.964** |</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Blue rows add Kalman-filtered motion. Bold marks the best value in each score column.</span><span class="co">]</span>{.metric-key}</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>At cutoff 0.50, filtering gives the same identity scores as the other two methods. At 0.40, it gives 295 accepted identity matches, compared with 278 for last-box matching and 262 for two-observation motion. This gives identity precision $295/304\approx 0.970$ and identity recall $295/306\approx 0.964$.</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>For this filtered run at 0.40, every accepted detection match also has the identity chosen by the sequence-wide pairing. Identity precision and recall therefore equal detection precision and recall. The scores remain below 1 because there are nine unmatched predicted boxes and eleven missed annotation boxes.</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>We can also add the filtered runs to the IDF1, MOTA and HOTA comparison. These scores again use the actual assigned detections from fresh frames 50–100 runs, not filtered position estimates. IDF1 and MOTA use evaluation IoU 0.50; HOTA is averaged over the 19 thresholds from 0.05 to 0.95.</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>| Confidence cutoff | Tracking method | IDF1 | MOTA | HOTA | ID switches |</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>|:---|:---|---:|---:|---:|---:|</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>| 0.50 | Last-box | **0.8391** | 0.9118 | 0.6758 | 4 |</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>| 0.50 | Two-observation motion | **0.8391** | **0.9150** | **0.6793** | **3** |</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>| 0.50 | Kalman-filtered motion | **0.8391** | **0.9150** | **0.6793** | **3** |</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>| 0.40 | Last-box | 0.9115 | 0.9314 | 0.7153 | 1 |</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>| 0.40 | Two-observation motion | 0.8590 | 0.9248 | 0.6703 | 3 |</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>| 0.40 | Kalman-filtered motion | **0.9672** | **0.9346** | **0.7375** | **0** |</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>Bold again marks the best values within each confidence group, including ties. The ID switches are counted by the same CLEAR evaluation used in MOTA.</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>At confidence cutoff 0.40, filtering gives the highest of these scores in this window, while two-observation motion scores below last-box.</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a><span class="fu">### Restarting over the full clip</span></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>The scores above describe runs that begin at frame 50 and end at frame 100. We now compare last-box matching and filtered motion over the full clip, frames 1–142, using confidence cutoff 0.40. Both trackers start afresh at frame 1, so their track IDs differ from those in the earlier example. In this run, T2 labels the orange-shirted player. At frame 116, a duplicate detection creates a second track, T12, for the same player.</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="al">![Last-box matching (top) and Kalman-filtered motion (bottom) when duplicate detections create competing tracks.](&lt;attachments/tracking/basketball-filtering-failure119.png&gt;)</span>{#fig-tracking-basketball-filtering-failure119 width=100% fig-alt="Last-box matching (top) and Kalman-filtered motion (bottom) when duplicate detections create competing tracks."}</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>At frame 119, last-box matching keeps T2, while filtered motion assigns the detection to T12. The T2 reference box has IoU 0.776 with the detection under last-box matching, and 0.743 when predicted from the filtered state. The competing T12 reference has IoU 0.749 in both runs. All these overlaps are above the acceptance cutoff of 0.30, but the one-to-one assignment selects a different track in each case.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>With the settings used here, adding Kalman filtering gives a local improvement in the assigned track IDs but no clear overall advantage over last-box matching across this short clip. Missing detections and competing tracks created by duplicate boxes still cause problems.</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>A clearer benefit can arise for an object moving a substantial distance between frames at roughly constant speed and direction, with noisy position measurements. The motion model predicts beyond the last observed box, while the filter combines observations over time to reduce the effect of individual detection errors on the position and velocity estimates.</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>*Source images: [TrackID3x3](https://doi.org/10.1145/3728423.3759400), [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).*</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="ot">[^filter-noise]: </span>Per image coordinate, we use a measurement-error standard deviation of 4 pixels and an acceleration-noise standard deviation of 1 pixel/frame². A new track starts with zero estimated velocity, position standard deviation 4 pixels and velocity standard deviation 10 pixels/frame.</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="fu">## Practical trackers and appearance information</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>We have used three ways to form the reference box for matching a track to a new detection:</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>| Reference | How we form it |</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>|:--|:--|</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>| Last observed box | Use the box from the most recent detection assigned to the track. |</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>| Two-observation motion | Estimate velocity from the two most recent observations and predict the next box. |</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>| Kalman-filtered motion | Predict from position and velocity estimates that combine earlier predictions and observations. |</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>A complete tracker combines its motion model and matching method with rules for starting, confirming and ending tracks. The following methods illustrate different combinations of these ideas:</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>| Method | Main ideas |</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>|:--|:--|</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>| <span class="co">[</span><span class="ot">SORT</span><span class="co">](https://doi.org/10.1109/ICIP.2016.7533003)</span> | Kalman box prediction, IoU association and track management. |</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>| <span class="co">[</span><span class="ot">Deep SORT</span><span class="co">](https://doi.org/10.1109/ICIP.2017.8296962)</span> | Kalman motion prediction and learned appearance information for association. |</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>| <span class="co">[</span><span class="ot">ByteTrack</span><span class="co">](https://doi.org/10.1007/978-3-031-20047-2_1)</span> | Kalman motion prediction; match high-confidence detections first, then use lower-confidence detections to update remaining active tracks. |</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>| <span class="co">[</span><span class="ot">BoT-SORT</span><span class="co">](https://arxiv.org/abs/2206.14651)</span> | ByteTrack-style association with a revised box-motion model, camera-motion compensation and optional appearance matching. |</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>Our small filter-based tracker shares its basic structure with SORT, although SORT also models box size and has different track-confirmation and expiry rules. We can now consider two further sources of information used by these methods: detection confidence and appearance.</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a><span class="fu">### Using confidence differently for updates and new tracks</span></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>In our simple loop, an unmatched detection that passes the confidence cutoff starts a new track. ByteTrack separates the evidence needed to update a track from that needed to start one. It first matches high-confidence detections to existing tracks. It then tries lower-confidence detections against the remaining unmatched active tracks. These lower-confidence boxes can update those tracks, but cannot start new ones.</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>In our frames 50–100 test, the high threshold is 0.50 and the second stage uses scores between 0.10 and 0.50. It supplies six additional player observations compared with the same ByteTrack given only high-confidence inputs, including observations of the red and black players at frame 65. The benefit of this second stage is fewer gaps in the assigned detections.</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>At frame 73, the box with confidence about 0.69 updates T6. The overlapping box with confidence about 0.42 is unused: T6 has already been matched, and this lower-confidence box cannot start a new track. It therefore avoids the extra record created by our simple tracker at cutoff 0.40.</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a><span class="al">![ByteTrack's supplied detections and assigned observation at frame 73.](&lt;attachments/tracking/bytetrack-frame73.png&gt;)</span>{#fig-tracking-bytetrack-frame73 width=100% fig-alt="ByteTrack's supplied detections and assigned observation at frame 73."}</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>Allowing weak observations can also affect later associations. In our full-clip test with high threshold 0.40, enabling the lower-confidence updates recovered additional observations but also produced more ID changes and duplicates than withholding those boxes.</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="fu">### Using the image inside the box</span></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>The image inside each box provides another source of information about which player it belongs to. A network trained for **person re-identification (ReID)** maps a cropped person image to a vector of features, or an **appearance embedding**. Its training encourages different images of the same person to have similar vectors. The tracker can compare a new crop with earlier crops assigned to a track, alongside its comparison of box positions.</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>We tested BoT-SORT with its appearance component switched off and on, keeping the other settings and supplied detections the same. Both runs cover frames 50–100 with high threshold 0.50. Camera-motion compensation is switched off for our fixed-camera video, and the appearance network is pretrained rather than trained on this basketball sequence.</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>At frame 71, both runs label the red player T2 and the black player T4. Both assign T4 to the red player at frame 73. With appearance enabled, the red player regains T2 at frame 74 and the black player regains T4 at frame 76. Without appearance, the red player remains T4 and the black player T2 through the rest of the run. The figure shows the assigned detection boxes.</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="al">![BoT-SORT associations with appearance off (top) and on (bottom).](&lt;attachments/tracking/botsort-appearance.png&gt;)</span>{#fig-tracking-botsort-appearance width=100% fig-alt="BoT-SORT associations with appearance off (top) and on (bottom)."}</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>Appearance can also favour a duplicate detection. In a run starting at frame 1 with the same high threshold of 0.50, the appearance-enabled tracker selects a lower-confidence duplicate at frame 27 because its crop is slightly more similar to the track's stored appearance. The other, higher-confidence box then starts an additional track. Both crops depict the same player: appearance similarity alone does not select the better-localised box or prevent a duplicate record. The way the tracker combines appearance, confidence and track-management rules therefore still matters.</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>*Source images: [TrackID3x3](https://doi.org/10.1145/3728423.3759400), [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).*</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a><span class="fu">## Modern directions: promptable video segmentation</span></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>In <span class="co">[</span><span class="ot">Image analysis tasks</span><span class="co">](image_tasks.qmd)</span>, we introduced **instance segmentation**, which identifies the pixels belonging to each separate object. This gives us a pixel mask for each player. We can also follow these masks through a video, keeping a consistent ID for each player.</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>Models such as <span class="co">[</span><span class="ot">**SAM 3**</span><span class="co">](https://ai.meta.com/research/sam3/)</span> support this kind of tracking. We can select an object using a **box prompt**: a rectangle indicating which object we want the model to segment and follow.</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>Here we use the **six YOLO11n detections from frame 50 as initial box prompts**. These are the same boxes retained by our confidence threshold of 0.50 and court filter. We give the selected objects IDs S1–S6, and SAM 3 predicts a mask for each one.</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a><span class="al">![Frame 50: the YOLO boxes on the left provide the initial prompts; SAM 3 predicts the masks on the right. Source: TrackID3x3, CC BY 4.0; masks, overlays and layout added.](&lt;attachments/tracking/sam3-initial-prompts.png&gt;)</span>{#fig-tracking-sam3-initial-prompts width=100% fig-alt="Frame 50: the YOLO boxes on the left provide the initial prompts; SAM 3 predicts the masks on the right."}</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>After frame 50, we supply only the subsequent video frames, with no further YOLO detections or corrective prompts. SAM 3 uses each new image together with stored visual information from earlier frames to predict the six masks. In this example, it maintains the six identities through frame 100. The frames below show S2 and S4 remaining with the red- and black-shirted players as they overlap.</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a><span class="al">![The two focal players retain their IDs through the overlap. S2 follows the player initially selected in the red shirt, and S4 follows the player in the black shirt. Source: TrackID3x3, CC BY 4.0; masks, crops, overlays and layout added.](&lt;attachments/tracking/sam3-overlap.png&gt;)</span>{#fig-tracking-sam3-overlap width=100% fig-alt="The two focal players retain their IDs through the overlap. S2 follows the player initially selected in the red shirt, and S4 follows the player in the black shirt."}</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">SAM 3 tracking the six players, shown in slow motion.</span><span class="co">](&lt;attachments/tracking/sam3-50-100-slow.mp4&gt;)</span></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>This is online tracking: each step uses the current image and information from earlier frames. However, real-time tracking also requires processing to keep up with the video. In the experiment we ran SAM3 processed the frames more slowly than they would arrive from a live camera so could not be used for real-time tracking.</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>Video and images: <span class="co">[</span><span class="ot">TrackID3x3</span><span class="co">](https://doi.org/10.1145/3728423.3759400)</span>, <span class="co">[</span><span class="ot">CC BY 4.0</span><span class="co">](https://creativecommons.org/licenses/by/4.0/)</span>.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><a href="attribution.txt">Third-party sources and licences</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>